### ISSUE TITLE
some suggestions for annotation properties

### ISSUE THREAD

**Issue by balhoff** [sergeitarasov/PhenoScript#4]
Looking in this OWL output: https://github.com/g-montanaro/phenoscript_grebennikovius/blob/main/main/output/grebennikovius.owl

There are a few properties I suggest changing. There is a mix of `DC` (http://purl.org/dc/elements/1.1/) and `DC Terms` (http://purl.org/dc/terms/) usage. I suggest standardizing on `DC Terms` for all usages (it contains all the `DC` properties). Some examples:

- `http://purl.org/dc/elements/1.1/contributor` -> `http://purl.org/dc/terms/contributor`
- `http://purl.org/dc/elements/1.1/source` -> `http://purl.org/dc/terms/source`
- `http://purl.org/dc/terms/requires` -> good

Secondly, I would avoid using the `oboInOwl` namespace for these files:
- `http://www.geneontology.org/formats/oboInOwl#created_by` (indicating tool generator) -> `http://purl.org/pav/createdWith`
  - One issue here is that `pav:createdWith` is an ObjectProperty, so really you need an IRI for `phenospy-0.230` to use as the value
- `http://www.geneontology.org/formats/oboInOwl#creation_date` -> `http://purl.org/dc/terms/created`

**Comment by sergeitarasov** [comment]
Thanks Jim, all suggestions are incorporated!

Do you think that instead of `http://www.geneontology.org/formats/oboInOwl#created_by`  it is ok to use `http://purl.org/dc/terms/creator` for `phenospy-0.230`?

**Comment by balhoff** [comment]
> Do you think that instead of `http://www.geneontology.org/formats/oboInOwl#created_by` it is ok to use `http://purl.org/dc/terms/creator` for `phenospy-0.230`?

I suppose so—I usually think of `creator` as a person, but the definition is pretty general.

**Comment by sergeitarasov** [comment]
Amended.
